### ISSUE TITLE
 VS Build Config 

### ISSUE THREAD

**Issue by wenhuancai** [Cylix/cpp_redis#110]
hi! 
I see "Add Visual C++ Build Config" for Pull requests. I wander if Vs2013/2015 is Support.
can you write make/link for windows.
  
I know Cmake ,it can  compile for MSVC. 

VS2017 is new,and few people reuse.
thank you for Cylix.

**Comment by Cylix** [comment]
Hi,

I focused on the latest release `4.0.0` during the past few weeks and didn't have the opportunity to focus again on that PR.

For now, I doubt I will merge this PR as is mostly because files were generated by hand while I'd prefer to generate it using CMake.

I would still need some investigation to check how other libraries deal with multiple MSVC versions: do they publish multiple solutions for each version or is there a universal way to do it?
As soon as I get these kinds of questions solved, I would be glad to add that in the repository though.

Best

**Comment by Cylix** [comment]
#97 has been merged, closing this issue.
