### ISSUE TITLE
Deadlock when co-operate between future_client & subscribers

### ISSUE THREAD

**Issue by huanncbg** [Cylix/cpp_redis#134]
Hi Cylix, I have an issue with future_client and subcriber.

`#include <string>
#include <cpp_redis/cpp_redis>

using namespace std;
using namespace cpp_redis;

int main()
{
    future_client client;
    client.connect();
    client.auth("goldpot@rd");
    client.sync_commit();
    redis_subscriber sub;
    sub.connect();
    sub.auth("goldpot@rd");
    sub.commit();

    cout << "redis_subscriber for listen on data changed, future_client will read keys has changed.\n";

    sub.psubscribe("__keyevent*__:*",[&client](const string &event, const string &key){
        string action = event.substr(event.find(":") + 1);
        cout << "action = " << action << ", key = " << key << endl;

        // Blocking issue if trying to use future_client to read data from redis
        cout << "key type =  " << client.type(key).get().as_string() << endl;
    });
    sub.commit();
    getchar();
}`

**Comment by Cylix** [comment]
Hi @huanncbg ,

First of all, I just want to advise you to upgrade to a more recent version of cpp_redis if you can as the version you are currently using is not maintained anymore and several improvement and fixes have been implemented.

Concerning your issue, the problem is that you are using a blocking operation from within the subscribe callback.
The subscribe callback is executed on an IO service thread from the network library and until this callback has not returned, this thread can't be used for any other networking operations.

In other words, your future_client blocking operation cannot be executed because you are blocking the networking thread that is supposed to process the callback to transmit the reply.

You have two different approaches to solve this issue.
By default, you have 1 io service worker. You can increase this number by calling `tacopie::get_default_io_service()->set_nb_workers(N);`. Even though that may appear as a working solution, I do not advise to solve your issue by doing so as it might appear if you got multiple callbacks getting called and all trying to process blocking operations from within the callback.

The other approach that I advise you to do is to make your blocking operation from within one of your own thread. Simply spawn an std::thread (or re-use one if you have a thread pool) to make your operation asynchronously. You can also maybe use the asynchronous redis client instead that you can safely use from within any callback with .commit().

Let me know if you need any other explanation in case my answer is confusing, or if you have any other questions/issues.

Best

**Comment by huanncbg** [comment]
In recent version of cpp_redis, you're  merging future_client & redis_client into a single class name client.
But this may confusing developer of which method is blocking or asynchronous, so it's easy to leading to to block io_service thread.

**Comment by Cylix** [comment]
You are right, I'll make it clearer in the documentation as soon as I can :)
Thanks for your feedback!
