### ISSUE TITLE
Passing wchar_t to the functions

### ISSUE THREAD

**Issue by PerduGames** [Cylix/cpp_redis#141]
I'm confused as I would to pass the parameter to the functions. For in my program I have to deal with **wchar_t** and the functions of cpp_redis are asking for **std::string(char)**, I do not know if it is possible to do this conversion. I tried some forms here without success.

**Comment by PerduGames** [comment]
I think I've been able to solve this, but I'm not sure because I have not been able to compile for testing yet.

**Comment by Cylix** [comment]
Hi,

Sorry for the late reply.
wchar_t is a compiler-dependent type, thus it is not supported and will not be supported by cpp_redis.
In order to use cpp_redis, you have to convert you wchar_t strings into the standard std::string.

There is apparently a quick way to do so (probably introducing loss of information if wchar_t stores characters in more than one byte?).

I'm closing this issue, but do not hesitate to re-open it if you have any other questions related to that subject.

Best
