### ISSUE TITLE
Error "undefined reference to" Linking Program 

### ISSUE THREAD

**Issue by PerduGames** [Cylix/cpp_redis#143]
I'm trying to compile two days, but I always get linking errors, I'm trying to compile a module with godot (a game engine), I'm not sure where the error may be, but I've never had problems linking libraries when compiling modules on godot. The error is this:

```
[ 97%] Linking Program        ==> bin/godot.x11.tools.64
modules/libmodules.x11.tools.64.a(gdredis.x11.tools.64.o): In function `GDRedis::GDRedis()':
/home/noloop/godot-3.0-20out2017/modules/gdredis/gdredis.cpp:5: undefined reference to `cpp_redis::client::client()'
modules/libmodules.x11.tools.64.a(gdredis.x11.tools.64.o): In function `GDRedis::~GDRedis()':
/home/noloop/godot-3.0-20out2017/modules/gdredis/gdredis.h:17: undefined reference to `cpp_redis::client::~client()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```

I do not understand why it tells me this "In function `GDRedis::~GDRedis()':" being that neither destructor has in my code. I've tried everything I imagined it could be, and I have no idea what to try.

What can you tell me when you speak"undefined reference to"?

**Comment by Cylix** [comment]
Hi,

I suppose your GRedis object contains an instance of the cpp_redis::client class.
When the GRedis destructor is called, it will call the cpp_redis::client destructor.

cpp_redis::client::~client should be part of the cpp_redis lib once compiled.
May I ask you to double check that your program is linked against libcpp_redis.a (-lcpp_redis -L/path/to/cpp_redis on unix or in the MSVC linkage options on windows).
If it is the case, you may try to remove the library and to rebuild it, then to retry to link with it.
If it still fails, may I ask you to run `nm libcpp_redis.a` on unix so that we can see what your libcpp_redis.a contains?

Best

**Comment by PerduGames** [comment]
I'm linking like this, I already tried several syntaxes and none worked:

https://github.com/PerduGames/gdredis/blob/master/SCsub

the file with the output of "nm /usr/local/lib/libcpp_redis.a":
[nmlibcpp.txt](https://github.com/Cylix/cpp_redis/files/1534397/nmlibcpp.txt)

**Comment by Cylix** [comment]
Hi,

sounds more like a build tool configuration issue, the libcpp_redis.a looks fine.

I checked out a bit online: https://github.com/godotengine/godot/blob/master/platform/x11/detect.py#L252

Can you try using `LINKFLAGS ` instead of `LIBS` in the same way this example is doing it?

Best

**Comment by PerduGames** [comment]
I'll test, anyway I apologize, I think it can be closed, it should not be a problem with cpp_redis. I can even compile everything "manually" doing so in SCsub:

```
# SCsub
Import('env')

env.Append(CPPPATH=['cpp_redis/includes/cpp_redis', 'cpp_redis/tacopie/includes/tacopie', '.'])
src_list = Split("""gdredis.cpp
                    register_types.cpp
                    cpp_redis/sources/builders/array_builder.cpp
                    cpp_redis/sources/builders/builders_factory.cpp
                    cpp_redis/sources/builders/bulk_string_builder.cpp
                    cpp_redis/sources/builders/error_builder.cpp
                    cpp_redis/sources/builders/integer_builder.cpp
                    cpp_redis/sources/builders/reply_builder.cpp
                    cpp_redis/sources/builders/simple_string_builder.cpp
                    cpp_redis/sources/core/client.cpp
                    cpp_redis/sources/core/reply.cpp
                    cpp_redis/sources/core/sentinel.cpp
                    cpp_redis/sources/core/subscriber.cpp
                    cpp_redis/sources/misc/logger.cpp
                    cpp_redis/sources/network/redis_connection.cpp
                    cpp_redis/sources/network/tcp_client.cpp
                    cpp_redis/tacopie/sources/network/common/tcp_socket.cpp
                    cpp_redis/tacopie/sources/network/unix/unix_self_pipe.cpp
                    cpp_redis/tacopie/sources/network/unix/unix_tcp_socket.cpp
                    cpp_redis/tacopie/sources/network/windows/windows_self_pipe.cpp
                    cpp_redis/tacopie/sources/network/windows/windows_tcp_socket.cpp
                    cpp_redis/tacopie/sources/network/io_service.cpp
                    cpp_redis/tacopie/sources/network/tcp_client.cpp
                    cpp_redis/tacopie/sources/network/tcp_server.cpp
                    cpp_redis/tacopie/sources/utils/error.cpp
                    cpp_redis/tacopie/sources/utils/logger.cpp
                    cpp_redis/tacopie/sources/utils/thread_pool.cpp""")
env.add_source_files(env.modules_sources, src_list)
```

**Comment by Cylix** [comment]
Sure, no problem :)

I'll close this issue then but do not hesitate to re-open it if you feel the need.

Best

**Comment by PerduGames** [comment]
I am receiving this when compiling as above, it seems that it is connecting, because I receive the signal that connected, but soon after giving this error and close:

```
terminate called after throwing an instance of 'cpp_redis::redis_error'
  what():  connect() failure
```

**Comment by Cylix** [comment]
Seems like the client could not connect to the server.
Are you running an instance of the redis-server somewhere? If so, make sure you specify the right host and port when connecting.

`I receive the signal that connected`: which signal?

Best

**Comment by PerduGames** [comment]
I'm connecting to the loopback on port 6379. The "sign" meant here where it tells me "client connected":

```
 client.connect("127.0.0.1", 6379, [this](const std::string& host, std::size_t port, cpp_redis::client::connect_state status) {
    if (status == cpp_redis::client::connect_state::dropped) {
      std::cout << "client disconnected from " << host << ":" << port << std::endl;
    }else{
         std::cout << "client connected" << std::endl;
    }
  });
```

**Comment by Cylix** [comment]
Your assumption is erroneous: status can be lots of things, not just dropped or connected: https://cylix.github.io/cpp_redis/html/classcpp__redis_1_1client.html#a2512bd48dd45391249a69bd720c1e4da

I guess you get notified when the connection started.
There are multiple states such that people willing to take actions depending on all possible connection states can, especially when reconnection for high availability is set up.

I'm confused concerning the loopback?
Is there anything running on port 6379?
At my knowledge, loopback is just a hardware component handling localhost network, but if you are not running anything on the given port (in this case, the redis-server), then connection will fail.

What happens if you run `nc 127.0.0.1 6379 -v` in your terminal?

Best

**Comment by PerduGames** [comment]
now here it is working. I'm using it now:

`... else if(status == cpp_redis::client::connect_state::ok){ ...
`

"I'm connecting to the loopback" = I'm running redis-server at 127.0.0.1 in port 6379. XD
It was a problem here, as I restarted the redis-server and started working.
