### ISSUE TITLE
store cpp_redis::client in class member

### ISSUE THREAD

**Issue by tilmanotto** [Cylix/cpp_redis#144]
Hi Cylix,

I want to store the opened instance client in a class member. Another way would be to create a centralised method for conneting with redis and returing the client. Unfortunately the compilers is always throwing this error:
use of deleted function ‘cpp_redis::client::client(const cpp_redis::client&)’

Do you have an idea?

Regards,

Tilman

Code example:

using namespace cpp_redis;

class Db {
public:
    Db();
    Db(const Db& orig);
    virtual ~Db();
    
    client open() {
      client cl;
      cl.connect("127.0.0.1", 6379, [](const std::string& host, std::size_t port, cpp_redis::client::connect_state status) {
    if (status == cpp_redis::client::connect_state::dropped) {
      std::cout << "client disconnected from " << host << ":" << port << std::endl;
    }
  });

    cl.sync_commit();

    return cl;
  }
    
private:
  
};

**Comment by Cylix** [comment]
Hi,

`cpp_redis::client`, `cpp_redis::subscriber`, and `cpp_redis::sentinel` have their copy constructor deleted, thus preventing them to be copied.

This implies that any of the instances of these classes can't be copied.

The main reason is that it makes it less error prone (impossible to copy your clients and mess up with the buffers/callbacks) and also because each client is linked to a specific underlying TCP socket which is unsafe to copy and not meant to be shared by multiple instances of a client.

If you want to store a client in an object that can be copied, you might want to use a shared pointer (for example, storing an `std::shared_ptr<cpp_redis::client>` rather than a raw `cpp_redis::client`).

Let me know if this solves this issue.

I'm closing this issue, but do not hesitate to reopen it if necessary.

Best
