### ISSUE TITLE
there have a problem of function connect  on linux

### ISSUE THREAD

**Issue by qqwx1986** [Cylix/cpp_redis#158]
void connect(
    const std::string& host                    = "127.0.0.1",
    std::size_t port                           = 6379,
    const connect_callback_t& connect_callback = nullptr,
    std::uint32_t timeout_msecs                = 0,
    std::int32_t max_reconnects                = 0,
    std::uint32_t reconnect_interval_msecs     = 0);

if i set timeout_msecs >0  the connect may throw exception which info with "time out "
there only happened in linux(ubuntu16.04) ,there no problem on windows

**Comment by Cylix** [comment]
Hi,

This might be the expected behavior.

timeout_msec is the maximum time to connect to the redis server. If the client takes more than timeout_msec to connect to the redis-server, then we will a timeout exception even though you might have successfully be able to connect after a while.

Leaving the timeout_msec to 0 does not set any timeout on the connection, meaning that it will either success (connected successfully) or failed (connection failed or rejected) but not timeout. On the other hand, it might lead the client to be stuck on the connection for a few seconds, which may or may not be desirable depending on your application.

I'm closing this issue but feel free to reopen it if you have any other questions.

Best!
