### ISSUE TITLE
Problems with a sync_commit after hmget

### ISSUE THREAD

**Issue by boflexman** [Cylix/cpp_redis#164]
Hey,

I have a problem regarding the sync_commit after executing the hmget function. 
The following (stripped code) scenario doesn´t give me any callback:

---HMGET---
cpp_redis::client m_redisClient;
m_redisClient.connect();

std::string key = "testKey";
std::vector<std::string> fields;
fields.push_back("/testField1");
fields.push_back("/testField2");

if(redisClient.is_connected())
{
    string tmp;
    m_redisClient.hmget(key, fields,
                                    [&](cpp_redis::reply& reply)
                                    {
                                         if(!reply.is_null())
                                             tmp = reply.as_string();
                                    });
    m_redisClient.sync_commit();  //endless loop
}
---END OF HMGET----

The connection in this scenario is alive, but after the execution of the function sync_commit, I´m captured in an endless loop.

Simultaneously, if I´m using the function hget and after that I´m calling a sync_commit, there is no problem and I get the correct value from my test redis database: 

---HGET---
cpp_redis::client m_redisClient;
m_redisClient.connect();

std::string key = "testKey";
std::string field= "testField";

if(redisClient.is_connected())
{
    string tmp;
    m_redisClient.hget(key, field,
                                    [&](cpp_redis::reply& reply)
                                    {
                                         if(!reply.is_null())
                                             tmp = reply.as_string();
                                    });
    m_redisClient.sync_commit();  //works fine 
}
---END OF HGET----

Shouldn´t I use the sync_commit function in the hmget scenario? I can´t see any difference why I shouldn´t use the sync_commit after I´m using the hmget compared to the hget function.  
Is this the correct handling how I should use the functions from your library? 

I really appreciate any help you can provide.

Best regards

**Comment by wenhuancai** [comment]
`m_redisClient.hmget(key, fields,
[&](cpp_redis::reply& reply)
{
if(!reply.is_null())
tmp = reply.as_string();
});`
it is error.
because define is 
` std::future<reply> hmget(const std::string& key, const std::vector<std::string>& fields);`
const std::vector<std::string>& fields) is not string.Hmget is all taken out.
The difference between hget and hmget is the difference between more and less.

**Comment by Cylix** [comment]
Hi @boflexman,

As mentioned by @wenhuancai, you indeed have an issue in the way you get the reply by HMGET.
HMGET returns an array rather than a string.

Still, I want to confirm with you concerning the endless loop: do you mean that .sync_commit never returns or the logic of your program leads you to keep looping until you receive a reply from HMGET (which you never get)?
If sync_commit never returns, then there may be an issue.

Best

**Comment by boflexman** [comment]
Hey @wenhuancai @Cylix 

Yeah i see, the return parameter of the hmget function is wrong from my side. 

This looks like the fix of my problem ;) 

It looked like the .sync_commit never returned, but the logic of my program has led to this behaviour.

Many thanks to you both.
