### ISSUE TITLE
connecte and reconnect

### ISSUE THREAD

**Issue by Clinkz24** [Cylix/cpp_redis#170]
I use my own network library, but there is a problem that bothers me. why **cpp_redis::network::tcp_client_iface::connect** is synchronous, when cpp_redis call reconnect, connect will block a thread in thread pool.

**Comment by Cylix** [comment]
Hi @Clinkz24 ,

I understand your point of view and it was also requested by someone else in the past (don't recall the issue).
I would love to change the design to do so (having an async connect as well as a sync version like sync_connect, in the same way we got a commit and sync_commit).

It is recorded on my list of improvement, but to be honest, I kind of lack time to do so currently as I'm working on more than 3 different open-source projects as the main (co-)maintainer.

PR are welcome if you are willing to provide the change (even if not perfect, it is usually pretty fast for me to do some final adjustments, that's what I did for the windows port or the sentinel support for example). Otherwise, I can't really give you any timeline concerning this change other than "some day".

I'm closing the issue, but feel free to re-open or leave a comment if you feel the need.

Best
