### ISSUE TITLE
make install currently broken with master (2.2)

### ISSUE THREAD

**Issue by Kenterfie** [Cylix/cpp_redis#20]
make install stops currently on

CMake Error at cmake_install.cmake:40 (file):
  file INSTALL cannot find "/home/XXX/src/cpp_redis/build/bin".

with tag 2.1 everything is working fine

**Comment by Cylix** [comment]
This is a good catch!

The error occurred when trying to install the library without building the tests or the examples.
In that case, the bin folder was never generated, and the install was failing.

As I always build everything, including tests and examples, in my development environment, I actually never caught this.

Fortunately, the fix is trivial.

Thanks for the report!
