### ISSUE TITLE
io_service::shutdown hang on  for wait worker thread ,in windows

### ISSUE THREAD

**Issue by yanwei1983** [Cylix/cpp_redis#25]
io_service::shutdown when m_socks is empty,will hang on wait for io thread, but they never wake up

auto io_service = create_io_service();
io_service.reset();

**Comment by hellozombie** [comment]
This issue still exists for me when using cpp_redis in a DLL thread:

```cpp
DWORD WINAPI Run(LPVOID param) {
  cpp_redis::client client; // With this line, the DLL can not be unloaded from the process
  // It works if the above line is commented out.
  Sleep(1000);
  FreeLibraryAndExitThread((HMODULE)param, 0);
  return 0;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call,
  LPVOID lpReserved) {
  switch (ul_reason_for_call) {
    case DLL_PROCESS_ATTACH:
        CloseHandle(CreateThread(NULL, NULL, (LPTHREAD_START_ROUTINE)Run, hModule, NULL, NULL));
(hModule);
    case DLL_PROCESS_DETACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
      break;
  }
  return TRUE;
}
```

Do you know if the above code is related to this issue?

**Comment by Cylix** [comment]
Hi,

sorry for the late reply.
I think this issue must be unrelated as the network part of the library has been entirely rewritten since then.

However, using cpp_redis inside DLL thread is something that has never been tested as I'm not usually developing any windows software (so quite hard for me to see all the possible use cases).

From your example above, seems like you create a cpp_redis::client at the beginning of your DLL then call FreeLibraryAndExitThread. I'm not sure what is the behavior of FreeLibraryAndExitThread, but I guess that's the place where it hangs.
Most probably, it waits for all inner threads to be terminated which does not occur because the tacopie io service is still running.

You may try one of the following to solve your issue:
* Instead of having a cpp_redis::client object, have a pointer to a cpp_redis::client object and destroy it before calling FreeLibraryAndExitThread. For example, having a std::shared_ptr<cpp_redis::client> that you set to nullptr before callling FreeLibraryAndExitThread should do the trick
* Otherwise, you may also try to call `tacopie::set_default_io_service(nullptr)` (you may need to include <tacopie/network/io_service.hpp>) before calling FreeLibraryAndExitThread. That should also force the cleanup of all underlying threads and prevent a hang.

Just let me know if your problem is still unsolved after that.

Best

**Comment by mkubzin** [comment]
Hi Simon,

I have also noticed this problem with hanging at exit. Main function finishes successfully then the runtime moves on to destroying static objects. Eventually it gets to thread_pool’s destructor which calls thread_pool::stop. By this time all threads, except the main one, are dead. Line “m_tasks_condvar.notify_all();” never returns. If one puts a breakpoint on it and skips it in the debugger, then the application completes gracefully.

Thank you,
Mike

**Comment by hellozombie** [comment]
@Cylix Thanks! Calling `tacopie::set_default_io_service(nullptr)` works!

Regarding the first approach (`std::shared_ptr`), I haven't tried it but I guess it will not work, as in my actual code I'm already using `std::unique_ptr<redis::RedisClient> client` and `client.reset()` before `FreeLibraryAndExitThread`.
Anyway, with your second approach the DLL can be unloaded successfully now.
