### ISSUE TITLE
Multithreaded mismatch

### ISSUE THREAD

**Issue by Spide85** [Cylix/cpp_redis#47]
This line on both _tacopie_ and _cpp_redis_ CMakeLists.txt is causing problems on my environment (VS2015 with CMake 3.7):
`string(REPLACE "/MD" "-MT" ${flag_var} "${${flag_var}}")`

I get errors like `error LNK2038: mismatch detected for 'RuntimeLibrary': value
'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' `.
I just commented out these lines and it builds. But this makes it impossible to use this lib simply as a submodule in my project.

**Comment by Cylix** [comment]
Hi,

Sorry for the time to reply, I finally find the time to have a look.

I guess cpp_redis compiled fine when you tried to integrate it but the errors showed up when trying to link it with your project?

This is due to the Runtime Library configuration.
Apparently, most recent versions of VC++ require the Runtime Library to be the same for every library linked into the project.

So my guess is that our current configuration that forces the use of MT (static runtime library configuration) creates a conflict with your project or another library of your project which is based on MD configuration.

So we can' t really just comment out/remove these lines because, even if it will solve your issue, it will create an issue for other people that didn' t have one until now because their project is based on MT configuration.

So instead, I provided a new CMake variable, `MSVC_RUNTIME_LIBRARY_CONFIG` for which you can assign the configuration you want (/MT, /MD or other).

By default, this variable is set to /MT (as before).

Hope this will solve your issue :)

Feel free to re-open this issue if necessary.

Best
