### ISSUE TITLE
where is zadd?

### ISSUE THREAD

**Issue by nneesshh** [Cylix/cpp_redis#57]
hi, Thx for your great work.
I can't find zadd command.
Does it mean that I mjust create sorted sets through text command?
Is there a plan to implement it in future?

**Comment by Cylix** [comment]
Hi,

The zadd command has not been implemented since it has too many parameters combinations.
I plan to implement the missing commands in the future, but this is not a priority for now.

If you wish to use ZADD, you need to use the `.send()` function directly and to pass in the arguments you want using the vector as parameter.
This is definitely less convenient than using a dedicated function, but still works.

However, if you want to use a dedicated function and have time to implement it, you are free to make a PR :)

Please let me know if you have any other questions.

Best

**Comment by nneesshh** [comment]
Ok, I used send() function and it worked fine.
thx again

**Comment by Cylix** [comment]
Great!
