### ISSUE TITLE
Does this project support "connection pool" for the moment?

### ISSUE THREAD

**Issue by PayneJoe** [Cylix/cpp_redis#59]
As the title puts.

**Comment by Cylix** [comment]
Hi,

There is actually no `explicit` support for connection pooling.

By default, cpp_redis uses [tacopie](https://github.com/cylix/tacopie) for its network communication.
Tacopie does not do any connection pooling and cpp_redis does not do any on top of tacopie.

However, since yesterday with #58, it is possible to use cpp_redis without tacopie and to specify its own tcp_client implementation using the `cpp_redis::network::tcp_client_iface`.
From my point of view, you can do connection pooling at that place, but that requires some extra work considering the fact it is not provided by the cpp_redis itself.

I didn't have the time to write some documentation about that yet, but basically, you have to derive from [tcp_client_iface](https://github.com/Cylix/cpp_redis/blob/master/includes/cpp_redis/network/tcp_client_iface.hpp) and implement the abstract methods (connect, disconnect, is_connected, async_read, async_write) and make sure the async_read/async_write calls the given callbacks on completion.

Once done, you have to set [get_tcp_client](https://github.com/Cylix/cpp_redis/blob/master/sources/network/redis_connection.cpp#L35) such that it is a function that returns your own tcp_client (your derived class of tcp_client_iface).

There is an "example" [here](https://github.com/Cylix/cpp_redis/blob/master/includes/cpp_redis/network/tcp_client.hpp). That's basically the implementation used for `tacopie`.

So not explicitly available, but achievable if necessary, though not convenient I must admit.

For your information, I do not plan to integrate this feature in a near feature (but PR are welcome of course).

Best

**Comment by Cylix** [comment]
I close this issue but feel free to reopen it if necessary.
I'll also notify this ticket once the documentation about the custom tcp_client will be available.

Best

**Comment by PayneJoe** [comment]
Much appreciated, Cylix =)
