### ISSUE TITLE
Is it possible to use "sync_commit" in subscribe callback?

### ISSUE THREAD

**Issue by gidorah** [Cylix/cpp_redis#68]
Hi,
The code I am trying to run is below:

	auto func_subscribe_reply = [=](const std::string& chan, const std::string& msg) {

		std::cout << "subscribe_reply : " << chan << " || " << msg << "\n";

		client.get("test_value", [](cpp_redis::reply& reply) {
			std::cout << "get test_value: " << reply << std::endl;
			 if (reply.is_string())
				 std::cout << "test_value : " << reply.as_string() << "\n";
		}).sync_commit();

		// I need to use test_value in here.
	};

	subscriber.subscribe("test_channel", func_subscribe_reply).commit();

`m_sync_condvar` waits forever in `sync_commit`. `commit` is doing great but I need to use the `test_value` where I pointed out. I don't know even if my question is logical, please excuse my lack of knowledge.

Thank you.

**Comment by Cylix** [comment]
Hi,

The issue you are currently facing is due to the number of threads that can process the replies.

By default, there is only one thread.
Thus, this thread is busy by processing your subscriber callback (which basically hangs on the `sync_commit`) and the incoming redis_client requests replies won't be processed until the subscriber callback completes.

There are two ways to solve this issue:
* `tacopie`, the underlying network library, can be configured such that multiple threads process the server replies (implying that if one callback is blocking, other threads can still process the other replies). You can simply use the [IO_SERVICE_NB_WORKERS](https://github.com/Cylix/cpp_redis/wiki/Compilation-and-installation-options#custom-number-of-io_service-workers) CMake variable. Please note that this feature is still beta, so I can't guarantee you won't have any issue, but you can still give a look to see if it solves your issue.
* You can start a new thread in the callback, using `std::thread`. In this thread, you can do your `sync_commit` and process the response asynchronously inside this thread.

In my opinion, the second solution seems to be preferable for your problem. Even though you add multiple threads to process the server replies from `tacopie`, what happens if your subscriber get notified multiple times in a row: then all the threads might be busy processing all the subscriber callbacks. If it can't happen, then solution one can work.

If you are worried about the cost of spawning threads, you can still create a `thread pool` to create threads once. If necessary, `tacopie` provides one simple implementation that you can check out [here](https://github.com/Cylix/tacopie/blob/master/includes/tacopie/utils/thread_pool.hpp).

Let me know if it is unclear or if you have any other questions!

Best :)

**Comment by gidorah** [comment]
First solution you gave has solved the issue as you said. I will do some tests, but I guess will go with solution two after that. 

Thank you again.

**Comment by Cylix** [comment]
Awesome!

I close the issue but feel free to re-open it if you have any issue or additional questions.

Best
