### ISSUE TITLE
Whether the client is suitable for the Windows? 

### ISSUE THREAD

**Issue by pzw520125** [Cylix/cpp_redis#7]
Whether the client is suitable for the Windows? Compile the same steps?Thank you.

**Comment by Cylix** [comment]
Hi,

On the current version of the library, compilation has not been tested on Windows and no support is provided for this platform. So it is highly possible that the library does **not** compile on Windows and behavior is totally unexpected since it hasn't been tested.
However, it is possible that porting this current version to windows should require little work.

There should be a new version of the library in the next few days that will get rid of the Boost.Asio dependency and will be based on the raw socket API instead. However, no support will be provided immediately for windows and this new version will require a lot more work to port it.
