### ISSUE TITLE
ZADD? how to call zadd???

### ISSUE THREAD

**Issue by hzhsan** [Cylix/cpp_redis#81]
as the title.
 how to call zadd with cpp_redis.

**Comment by Cylix** [comment]
Hi,

As explained in #57 ([Where is zadd?](https://github.com/Cylix/cpp_redis/issues/57)), the zadd command has not been implemented since it has too many parameters combinations.

If you wish to use ZADD, you need to use the `.send()` function directly and to pass in the arguments you want using the vector as parameter.
This is definitely less convenient than using a dedicated function, but still works.

However, if you want to use a dedicated function and have time to implement it, you are free to make a PR :)

Since it is the second time this question is asked (maybe even more actually cos I remember receiving this question on my personal email), I think the documentation is not clear enough and I'll surely update it in the future to make it more clear.

Please let me know if you still have any other questions,

Best!
