### ISSUE TITLE
Deadlock when calling sync_commit from callback

### ISSUE THREAD

**Issue by dhirst2880** [Cylix/cpp_redis#82]
Hi,

I just encountered a deadlock while using the cpp_redis client. The following attachment can be used to demonstrate that the program will hang forever. Arguably, it might not be a good idea to call a sync_commit() from within a callback. However, there wasn't any documentation indicating that this wasn't possible. I'm not sure what an exact fix would be. Hopefully you find the test case useful.

Thanks!
-DH
[TestAccessServer.cpp.txt](https://github.com/Cylix/cpp_redis/files/1076081/TestAccessServer.cpp.txt)

**Comment by Cylix** [comment]
Hi,

The deadlock is absolutely normal and is an expected behavior.
The way sync_commit work is to block until all commands have been sent to the redis, but also until also server responses have been received and **processed**, including executing all the underlying callback.

I can understand the confusion though, especially when calling commit is fine but not sync_commit, so I'll update the documentation to clarify this point.

However, for now, this behavior will stay unchanged. The main reason is that calling sync_commit from a callback is dangerous: the number of threads dedicated to processing callback is fixed (1 by default) and this will neutralize one of those threads and eventually all of them.
There are some other ways to deal with that case, but they will add some extra complexity to the library and might be error prone, so I prefer to delegate this handling to the library user.

I'll close this ticket but do not hesitate to re-open it if you have any other concerns :)

Thanks again fro reporting that, other users might have encountered this issue and think this is a bug, so it really helps me improve the library and its documentation: I appreciate a lot!

Best!

**Comment by dhirst2880** [comment]
Hi,

I don't disagree with you. I would hope that when you update the library documentation, you could also include a warning that it's potentially unsafe for the callback handlers to block, as this will also likely result in a deadlock situation -- aka, I already experienced this problem as well :)

Thanks for  a nice C++ redis library!

**Comment by Cylix** [comment]
Hi,

I provided an update of the documentation in the `.commit()` part, but maybe I should consider also adding in the `.connect()` in the case some people might miss it? Probably in examples also.

Thanks for your feedback and glad that cpp_redis brought you satisfaction :)
