### ISSUE TITLE
missing `scan` support?

### ISSUE THREAD

**Issue by sumory** [Cylix/cpp_redis#83]

**Comment by Cylix** [comment]
Hi,

This question is related to #81 and #57 (concerning zadd).

Basically, as specified by the [wiki](https://github.com/Cylix/cpp_redis/wiki/Redis-Client#commands):
```
If a command is missing or that the method to call that command is not convenient, please consider using the send() method directly.

All the following member functions are wrappers for the send() function to provide more code clarity.
```

Currently, `ZADD` and `SCAN` (as well as some other commands) do not have any associated function in the `redis_client` because there are too many combinations of their parameters.

I'd like to provide such functions, but this is not a priority for now and I lack a bit time to do it.
However, if you feel you can do it, I'd be glad to merge a PR implementing this support.

You can still query SCAN command though, using the [send](https://github.com/Cylix/cpp_redis/wiki/Redis-Client#send) function:
`client.send({ "SCAN", "param1", "param2", ... })`.
This might appear as less convenient than simply calling a `.scan()`, but this still works and is basically the same (all other commands are actually a simple wrapper of `.send()`).

I'll close this issue but just let me know if you have any other questions.

Best :)
