### ISSUE TITLE
Does this library support cluster mode?

### ISSUE THREAD

**Issue by GrossoMoreira** [Cylix/cpp_redis#84]
Hi,

I've seen some "cluster_" functions in redis_client.hpp, but the documentation and the examples don't seem to have anything related to using this library to connect to multiple cluster nodes and use them transparently.

Can I connect to multiple masters such that the redis client knows which keys should be sent to which nodes?

Thank you!

**Comment by Cylix** [comment]
Hi,

I am not really familiar with Redis clusters but I'll try to answer you as best as I can :)

From my understanding, the cluster commands for which a wrapper is provided are just standing for live-reconfiguration of clusters that technically have to be configured using configuration files at first.

`cpp_redis` allows you to connect to multiple Redis servers simultaneously, so multiple masters.
However, there is no particular handling provided by cpp_redis concerning clusters, so it is possible that the current behavior might be inconvenient for cluster communication.
This might particularly apply if the messages sent by the server are not following the same way as normal redis client communication (request -> response) or redis sub communication (request -> stream of response). If so, some callbacks might not be called.

I never used redis clusters as for now, so I can't really tell if it can be use or not. I hope my answer will still bring you some clues. Otherwise, I guess you can try to see if it fulfills your needs but be aware that we do not officially support cluster and do not plan to bring support for clusters for now.

Best!

**Comment by GrossoMoreira** [comment]
What I expect from a wrapper that provides cluster commands is that it keeps track of the current configuration of the cluster (like you said) and sends the requests to the appropriate nodes according to how the keys were resharded in the cluster.

So, if I 'set x y' I expect it to know which node has the key 'x' and send the command to that node.

You said that this library can connect to multiple masters. Does it work as in the example above?

I'm very new to redis. Thank you for your patience!

**Comment by Cylix** [comment]
Hi,

I understand a bit more the use-case you are looking for.
Unfortunately, cpp_redis will not provide you such support right now.
I guess it can be done by building your own support on top of cpp_redis, but cpp_redis itself will not provide you this feature.

When connecting to multiple masters, you will just have multiple `redis_client`, but cpp_redis will not make any special handling.
It will just open several connections (one for each client) and provide support to communicate with the Redis server without knowing with the current connection is a connection to a master or not.

Do not hesitate if you have any other questions or if my comment does not fully answer your question :)

Best

**Comment by GrossoMoreira** [comment]
Ok, that settles it. Thank you very much!
