### ISSUE TITLE
Data type problem 

### ISSUE THREAD

**Issue by Dr13am** [Cylix/cpp_redis#95]
I donot understand this statement：    client.decrby("hello", 12, [](cpp_redis::reply& reply)   ，
this  statement  in  redis_client.cpp .
i want  to  know that  What‘s  the  meaning of " [](cpp_redis::reply& reply " ?

**Comment by Cylix** [comment]
Hi,

```cpp
[](cpp_redis::reply& reply) {
   std::cout << "hello world!" << std::endl;
}
```

This statement is what we call `lambdas` and it has been introduced since C++11.
It can be seen as an anonymous function (a function with no name) and is sometimes more practical to use that declaring a function and passing a pointer to that function.

Lambdas are composed y three different parts:

* `[]` is a block where you can specify how to capture the current context so that it can be used inside the lambdas. The most basic examples is `[=]` (capture everything by copy) and `[&]` (capture everything by reference). There exist some variation to help you capture only specific variable, or capture some variable by copy and some others by reference. By capture, I mean that you have some variables declared outside the lambda that you need to use inside the lambda: in such case, you have to `capture` them
* `(cpp_redis::reply& reply)`  is simply the lambda parameters (similar to function parameters)
* the remaning part (`{ ... }`) is simply the lambda body (similar to function body).

I advise you to take a deeper loop into the concept of lambdas and to get used to it as it is an important and useful concept of modern C++.

Last but not least, even though the example uses lambdas for code clarity, every function that takes a lambda as parameter are actually taking an std::function as parameter, meaning you can pass function pointer also (or any other callable).

Let me know if you have any other questions,

Best
